export { default as Cars } from './cars/Cars'
export { default as Crypto } from './crypto/Crypto'
export { default as Flights } from './flights/Flights'
export { default as Hero } from './hero/Hero'
export { default as CTA } from './cta/CTA'